/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasAlumno;

import Funciones.funcionesAlumno;
import static Vista.modulo_Administracion.datosCurso;
import static Vista.modulo_Administracion.graficaCursos;
import static Vista.modulo_Administracion.panelCurso;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import objetos.Actividad;
import objetos.Alumno;
import objetos.Curso;
import objetos.NotaAlumno;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import static vistasAlumno.moduloAlumno.alumnoLogeado;
import static vistasAlumno.moduloAlumno.cursoSeleccionadoAlumno;

/**
 *
 * @author lopez
 */
public class informacionCurso extends javax.swing.JFrame {

    public static DefaultTableModel modeloTablaAlumnoLogeado;
    public static DefaultCategoryDataset datosNotas = new DefaultCategoryDataset();
    public static ChartPanel panelNotas = null;
    public static float[] notasAlumno = new float[6];

    public informacionCurso() {
        initComponents();
        iniciar2();
        actualizarTablaAlumnoLogeado();
    }

    private void iniciar2() {
        //buscar el nombre del curso dentro del listado de cursos del usuario 
        for (Curso misCursos : alumnoLogeado.getListaCursosAsignados()) {
            if (misCursos.getCodigo() == Integer.parseInt(cursoSeleccionadoAlumno)) {
                tituloCursoAlumno.setText(misCursos.getNombreCurso());

            }

        }

    }

    public static void actualizarTablaAlumnoLogeado() {

        modeloTablaAlumnoLogeado = new DefaultTableModel() {

            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloTablaAlumnoLogeado.addColumn("nombre");
        modeloTablaAlumnoLogeado.addColumn("Descripcion");
        modeloTablaAlumnoLogeado.addColumn("Ponderacion");
        modeloTablaAlumnoLogeado.addColumn("Nota Obtenida");
        int contadorN = -1;
        for (Alumno alumnoCurso : funcionesAlumno.listaAlumnos) {

            for (Curso al : alumnoCurso.getListaCursosAsignados()) {
                //notasAlumno = new float[al.getListaActividades().size()];
                for (Actividad actividades : al.getListaActividades()) {

                    if (alumnoCurso.getCodigo() == alumnoLogeado.getCodigo()) {

                        if (actividades.getNombreCurso().equals(cursoSeleccionadoAlumno)) {
                            String[] fila = new String[4];
                            fila[0] = actividades.getNombre();
                            fila[1] = actividades.getDescripcion();
                            fila[2] = String.valueOf(actividades.getPonderacion());

                            for (NotaAlumno nta : actividades.getListaNotas()) {

                                if (nta.getCodigoAlumno() == alumnoLogeado.getCodigo()) {
                                    contadorN++;
                                    fila[3] = String.valueOf(nta.getNotaActividad());
                                    notasAlumno[contadorN] = nta.getNotaActividad();
                                }
                            }

                            modeloTablaAlumnoLogeado.addRow(fila);
                        }
                    }
                }
            }
        }
        tablaActividadesAlumno.setModel(modeloTablaAlumnoLogeado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloCursoAlumno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActividadesAlumno = new javax.swing.JTable();
        graficaActividad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloCursoAlumno.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tituloCursoAlumno.setText("jLabel1");

        jLabel2.setText("Actividades");

        tablaActividadesAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaActividadesAlumno);

        javax.swing.GroupLayout graficaActividadLayout = new javax.swing.GroupLayout(graficaActividad);
        graficaActividad.setLayout(graficaActividadLayout);
        graficaActividadLayout.setHorizontalGroup(
            graficaActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        graficaActividadLayout.setVerticalGroup(
            graficaActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tituloCursoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(graficaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tituloCursoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graficaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //datosCurso.setValue(, "Curso1", "a");
        try {
            datosNotas.setValue(notasAlumno[0], "1", "b");
            datosNotas.setValue(notasAlumno[1], "2", "b");
            datosNotas.setValue(notasAlumno[3], "3", "b");
            datosNotas.setValue(notasAlumno[4], "4", "b");
            datosNotas.setValue(notasAlumno[5], "5", "b");
            datosNotas.setValue(notasAlumno[6], "6", "b");
        } catch (Exception e) {
        }

        JFreeChart graficoBarraAlumno = ChartFactory.createBarChart3D("Actividades",
                "Actividad",
                "Cantidad",
                datosNotas,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        panelNotas = new ChartPanel(graficoBarraAlumno);
        panelNotas.setMouseWheelEnabled(false);
        panelNotas.setPreferredSize(new Dimension(graficaActividad.getWidth(), graficaActividad.getHeight()));

        graficaActividad.setLayout(new BorderLayout());
        graficaActividad.add(panelNotas, BorderLayout.NORTH);
        pack();
        repaint();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacionCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graficaActividad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tablaActividadesAlumno;
    private javax.swing.JLabel tituloCursoAlumno;
    // End of variables declaration//GEN-END:variables
}
