/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaAdmin;

//import static Funciones.funcionesUsuario.usuarios;
import Funciones.funcionesUsuario;
import static Funciones.funcionesUsuario.binario;
import static Funciones.funcionesUsuario.listaUsuarios;
import static Vista.modulo_Administracion.actualizarTabla;
import static Vista.modulo_Administracion.actualizarTablaCurso;
import static Vista.modulo_Administracion.limpiarG;
import static Vista.modulo_Administracion.llenarCombo;
import objetos.Usuario;
import static vistaAdmin.agregarCurso.profesorCurso;

/**
 *
 * @author lopez
 */
public class actualizarProfesor extends javax.swing.JFrame {

    public static Usuario usuarioModificable;

    public actualizarProfesor() {
        initComponents();
        initComponents2();

    }

    private void initComponents2() {
        codigoProfesorA.setText(String.valueOf(usuarioModificable.getCodigo()));
        nombreProfesorActualizado.setText(usuarioModificable.getNombre());
        apellidoProfesorActualizado.setText(usuarioModificable.getApellido());
        correoProfesorActualizado.setText(usuarioModificable.getApellido());
        passwordProfesorActualizado.setText(usuarioModificable.getPassword());

        if (usuarioModificable.getGenero().equals("F")) {
            generoProfesorActualizado.setSelectedIndex(0);
        } else if (usuarioModificable.getGenero().equals("M")) {
            generoProfesorActualizado.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        correoProfesorActualizado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        generoProfesorActualizado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        codigoProfesorA = new javax.swing.JTextField();
        apellidoProfesorActualizado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreProfesorActualizado = new javax.swing.JTextField();
        actualizarDatosProfesor = new javax.swing.JButton();
        passwordProfesorActualizado = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Contraseña");

        correoProfesorActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoProfesorActualizadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Actualizar Datos Profesor");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Género");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Código");

        generoProfesorActualizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        generoProfesorActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoProfesorActualizadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");

        codigoProfesorA.setEnabled(false);
        codigoProfesorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProfesorAActionPerformed(evt);
            }
        });

        apellidoProfesorActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoProfesorActualizadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Apellido");

        nombreProfesorActualizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProfesorActualizadoActionPerformed(evt);
            }
        });

        actualizarDatosProfesor.setText("Actualizar");
        actualizarDatosProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarDatosProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(correoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizarDatosProfesor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoProfesorA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordProfesorActualizado))
                        .addContainerGap(58, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoProfesorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoProfesorActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualizarDatosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoProfesorActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoProfesorActualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoProfesorActualizadoActionPerformed

    private void generoProfesorActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoProfesorActualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoProfesorActualizadoActionPerformed

    private void codigoProfesorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProfesorAActionPerformed

    }//GEN-LAST:event_codigoProfesorAActionPerformed

    private void apellidoProfesorActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoProfesorActualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoProfesorActualizadoActionPerformed

    private void nombreProfesorActualizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProfesorActualizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProfesorActualizadoActionPerformed

    private void actualizarDatosProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarDatosProfesorActionPerformed

   
        String nuevoNombre = nombreProfesorActualizado.getText();
        String nuevoApellido = apellidoProfesorActualizado.getText();
        String nuevoCorreo = correoProfesorActualizado.getText();
        String nuevoPassword = passwordProfesorActualizado.getText();
        String nuevoGenero = funcionesUsuario.valorComboBox(generoProfesorActualizado.getSelectedIndex());

        try {
            funcionesUsuario.actualizarUsuario(usuarioModificable, nuevoNombre, nuevoApellido, nuevoCorreo, nuevoPassword, nuevoGenero);
            profesorCurso.removeAllItems();
            actualizarTablaCurso();
            binario.guardarProfesorBinario(listaUsuarios);

        } catch (Exception e) {
        }

        //agregarCurso.modeloCombo.addElement(codigoP+"-"+nuevoNombre);
        actualizarTabla();


    }//GEN-LAST:event_actualizarDatosProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actualizarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actualizarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actualizarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actualizarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new actualizarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarDatosProfesor;
    private javax.swing.JTextField apellidoProfesorActualizado;
    private javax.swing.JTextField codigoProfesorA;
    private javax.swing.JTextField correoProfesorActualizado;
    private javax.swing.JComboBox<String> generoProfesorActualizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombreProfesorActualizado;
    private javax.swing.JPasswordField passwordProfesorActualizado;
    // End of variables declaration//GEN-END:variables
}
