/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasProfesor;

import static Funciones.funcionesAlumno.devolverPromedioAlumnoBajo;
import javax.swing.table.DefaultTableModel;
import static vistasProfesor.AdministracionCurso.listaA;
import static vistasProfesor.AdministracionCurso.listaPosicion;
import static vistasProfesor.PromedioAlto.modeloTablaNota;
import static vistasProfesor.moduloProfesor.cursoSeleccionado;

/**
 *
 * @author lopez
 */
public class PromedioBajo extends javax.swing.JFrame {

   public static DefaultTableModel modeloTablaBaja ;
    public PromedioBajo() {
        initComponents();
        //devolverPromedioAlumnoBajo(Integer.parseInt(cursoSeleccionado));
       // actualizarTablaAlumnosCurso();
    }
    
     public static void actualizarTablaAlumnosCurso() {

        modeloTablaBaja = new DefaultTableModel() {

            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloTablaBaja.addColumn("Nota");
        modeloTablaBaja.addColumn("Codigo");

                    String[] fila = new String[2];
                    fila[0] = String.valueOf(listaA[0]);
                    fila[1] = String.valueOf(listaPosicion[0]);
                    modeloTablaBaja.addRow(fila);
                    
                    String[] fila2 = new String[2];
                    fila2[0] = String.valueOf(listaA[1]);
                    fila2[1] = String.valueOf(listaPosicion[1]);
                    modeloTablaBaja.addRow(fila2);
                    
                    String[] fila3 = new String[2];
                    fila3[0] = String.valueOf(listaA[2]);
                    fila3[1] = String.valueOf(listaPosicion[2]);
                    modeloTablaBaja.addRow(fila3);
                
                    String[] fila4 = new String[2];
                    fila4[0] = String.valueOf(listaA[3]);
                    fila4[1] = String.valueOf(listaPosicion[3]);
                    modeloTablaBaja.addRow(fila4);
                    
                    String[] fila5 = new String[2];
                    fila5[0] = String.valueOf(listaA[4]);
                    fila5[1] = String.valueOf(listaPosicion[4]);
                    modeloTablaBaja.addRow(fila5);

            
        
        tablaNotabaja.setModel(modeloTablaBaja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotabaja = new javax.swing.JTable();

        tablaNotabaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotabaja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromedioBajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromedioBajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromedioBajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromedioBajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromedioBajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tablaNotabaja;
    // End of variables declaration//GEN-END:variables
}
